services:
  app:
    build:
      context: .

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production

    restart: unless-stopped
    init: true

    read_only: true

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL

    tmpfs:
      - /tmp:rw,noexec,nosuid,size=16m

    pids_limit: 100
    mem_limit: 256m
    cpus: "1.0"

    stop_grace_period: 10s
